### ISSUE TITLE
Website should integrate with social media

### ISSUE THREAD

**Issue by schwuk** [CodeCumbria/somebody-should#4]
As we start using the site for more than just a static landing page, it should be integrated into Social Media to make life easier.

**Comment by MechaCoder** [comment]
can we also integrate the slack sigin up as well ?

**Comment by adonaldson** [comment]
@MechaCoder I guess we could include a link. My only concern is that we'd get spammed, but we can worry about that if it happens!

**Comment by MechaCoder** [comment]
we could ask some very basic qwestions to prove that people are real- it how it is done on other slackgroups

**Comment by adonaldson** [comment]
let's just whack a link up and see what happens. We could maybe restyle the invite page to look more CodeCumbria'y

**Comment by schwuk** [comment]
We now have a handy-dandy Slack button on the site!

**Comment by schwuk** [comment]
Again, already done this. Via Jetpack, new posts are shared automatically to Twitter, Facebook and Google+, and Jetpack has recently introduced re-sharing of posts.
