### ISSUE TITLE
Website should integrate with Mailchimp

### ISSUE THREAD

**Issue by schwuk** [CodeCumbria/somebody-should#5]
Instead of creating mailshots _only_ within Mailchimp, which should be creating them as posts on the site and having those shared through Mailchimp.

**Comment by adonaldson** [comment]
Does this exist already or would we have to make it?

**Comment by schwuk** [comment]
Site now includes a Mailchimp sign up form.

**Comment by schwuk** [comment]
There should be something out there already.

**Comment by schwuk** [comment]
Forgot I'd already done this! Mailchimp now sends out all **new** posts each Monday.
