### ISSUE TITLE
January Meeting

### ISSUE THREAD

**Issue by schwuk** [CodeCumbria/somebody-should#6]
For the January meeting (Wednesday 25th) we need a few volunteers:

- Someone to wrangle the meeting: organising speakers (if any), preparing and sending out mailshots, social media pre-announcements, and write the post-meeting wrap-up etc.
- Someone to host the meeting: be there on time, let people in, make sure the coffee is on, etc.
- Someone to **MC** the meeting: open up the meeting, handle introductions, keep discussions to time, and make sure we wrap things up
- Someone to wrangle social media during the meeting: photos etc.

These can be one or (ideally - we want to spread the burden) multiple people. If you want to help out, assign yourself to this issue and add a comment to indicate which role(s) you want to fulfil, and we'll take it from there!

**Comment by MechaCoder** [comment]
I can do the social media if someone is willing to look over things I write.

**Comment by matthewroach** [comment]
I plan to work from the CBIC from around lunch time. So you can put my name down for the hosting part and getting the brew on

@schwuk Does not look like anyone is able to assign themselves to issues
